include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    no_leading_underscores_for_local_identifiers: ignore
    unnecessary_library_name: ignore
    use_string_in_part_of_directives: ignore


