name: quiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  hydrated_bloc:         # for state persistence
  supabase_flutter: ^2.9.1
  go_router: ^16.0.0             # for navigation
  intl:                  # formatting dates/scores
  equatable: ^2.0.7             # cleaner Bloc state comparisons
  shared_preferences:
  dio:
  google_sign_in_android: 
  google_sign_in_ios: 
  flutter_dotenv: ^5.2.1
  bloc: ^9.0.0
  fluttertoast: ^8.2.12
  # svg_flutter: ^0.0.1
  flutter_svg:
  flutter_material_design_icons: ^1.1.7447

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/task-list-menu-document-svgrepo-com.svg
    - images/categories/sports.svg
    - images/categories/fashion.svg
    - images/categories/music.svg
    - images/categories/science.svg
    - images/categories/general.svg

